# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
inhibit_all_warnings!
target 'Re0To1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Re0To1
  pod 'AFNetworking'
end
